llama-2-7b-chat-hf:
  prompt_template: "llama-2-7b-chat-hf/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "meta-llama/Llama-2-7b-chat-hf"
    model_kwargs:
      torch_dtype: 'float16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "LLaMA2 Chat 7B"
  link: "https://ai.meta.com/llama/"
