openbuddy-falcon-40b-v9:
  prompt_template: "openbuddy-falcon-40b-v9/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "./openbuddy-falcon-40b-v9-bf16" # local path
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "OpenBuddy-Falcon-40B-v9"
  link: "https://huggingface.co/OpenBuddy/openbuddy-falcon-40b-v9-bf16"
