zephyr-7b-beta:
  prompt_template: "zephyr-7b-alpha/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "HuggingFaceH4/zephyr-7b-beta"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Zephyr 7B Beta"
  link: "https://huggingface.co/HuggingFaceH4/zephyr-7b-beta"