vicuna-13b-v1.3:
  prompt_template: "vicuna-7b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "lmsys/vicuna-13b-v1.3"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Vicuna 13B v1.3"
  link: "https://huggingface.co/lmsys/vicuna-13b-v1.3"