vicuna-7b-v1.5:
  prompt_template: "vicuna-7b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "lmsys/vicuna-7b-v1.5"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Vicuna 7B v1.5"
  link: "https://huggingface.co/lmsys/vicuna-7b-v1.5"
