humpback-llama2-70b:
  prompt_template: "humpback-llama-65b/prompt.txt"
  fn_completions: ""
  completions_kwargs:
    model_name: "humpback-llama2-70b"
    max_length: 4096
    temperature: 0.7
    top_p: 0.9
  pretty_name: "Humpback LLaMa2 70B"
  link: "https://arxiv.org/abs/2308.06259"
