gpt-3.5-turbo-1106_ranking:
  prompt_template: "gpt-3.5-turbo-1106_ranking/ranking_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-3.5-turbo-1106"
    max_tokens: 100
    temperature: 0
  fn_completion_parser: "ranking_parser"
  batch_size: 1
