gpt-3.5-turbo-16k-0613:
  prompt_template: "gpt4/chatml_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-3.5-turbo-16k-0613"
    max_tokens: 3072
  pretty_name: "GPT 3.5 Turbo (06/13)"