gpt-3.5-turbo-1106:
  prompt_template: "gpt4/chatml_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-3.5-turbo-1106"
    max_tokens: 4096
  pretty_name: "GPT 3.5 Turbo (11/06)"