gpt4_1106_preview_concise:
  prompt_template: "gpt4_1106_preview_concise/chatml_prompt_concise.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4-1106-preview"
    max_tokens: 4096
  pretty_name: "GPT-4 Preview (concise)"