alpaca-farm-ppo-human:
  prompt_template: "alpaca-7b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "./alpaca_farm_ppo_human" # local path
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Alpaca Farm PPO Human 7B"
  link: "https://huggingface.co/tatsu-lab/alpaca-farm-ppo-human-wdiff"