guanaco-65b:
  prompt_template: "guanaco-7b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "./llama-65b" # local path
    adapters_name: "timdettmers/guanaco-65b"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Guanaco 65B"
  link: "https://huggingface.co/timdettmers/guanaco-65b"