falcon-40b-instruct:
  prompt_template: "alpaca-7b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "tiiuae/falcon-40b-instruct"
    model_kwargs:
      torch_dtype: 'bfloat16'
      trust_remote_code: True
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Falcon 40B Instruct"
  link: "https://huggingface.co/tiiuae/falcon-40b-instruct"